# 应用主配置
name: "web_app"
mode: "dev" # release
port: 8000
start_time: "2020-07-01"
machine_id: 1

# 日志配置
logs:
  level: "debug"
  logfilename: "./logs/webapp.log"
  max_size: 200
  max_age: 30
  max_backups: 7

# MYSQL数据库配置
mysql:
  mysqlhost: "192.168.56.120"
  mysqlport: 3306
  user: "root"
  # mysqlpassword: "Narwal#2021"
  mysqlpassword: "88888888"
  dbname: "bluebell"
  max_open_conns: 100
  max_idle_conns: 50

# REDIS数据库配置
redis:
  #redishost: "120.24.4.124"
  redishost: "192.168.56.120"
  redisport: 6379
  redispassword: "adl1314520"
  db: 1
  pool_size: 100